=== CapSylar/Luke-RNAwalker/DiffScriptDefinition.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Diff (meta,EditScript)>
<!ATTLIST Diff
        xmlns CDATA #FIXED ''>

<!ELEMENT meta (SourceString,DestinationString)>
<!ATTLIST meta
        xmlns CDATA #FIXED ''>

<!ELEMENT EditScript (Insert | Update | Delete)*>
<!ATTLIST EditScript
        xmlns CDATA #FIXED ''>

<!ELEMENT SourceString (#PCDATA)>
<!ATTLIST SourceString
        xmlns CDATA #FIXED ''>

<!ELEMENT DestinationString (#PCDATA)>
<!ATTLIST DestinationString
        xmlns CDATA #FIXED ''>

<!ELEMENT Insert (nucl,insertIndex,reverseIndex)>
<!ATTLIST Insert
        xmlns CDATA #FIXED ''>

<!ELEMENT Update (newNucl,oldNucl,updateIndex,reverseIndex)>
<!ATTLIST Update
        xmlns CDATA #FIXED ''>

<!ELEMENT Delete (nucl ,deleteIndex , reverseIndex)>
<!ATTLIST Delete
        xmlns CDATA #FIXED ''>

<!ELEMENT insertIndex (#PCDATA)>
<!ATTLIST insertIndex
        xmlns CDATA #FIXED ''>

<!ELEMENT updateIndex (#PCDATA)>
<!ATTLIST updateIndex
        xmlns CDATA #FIXED ''>

<!ELEMENT deleteIndex (#PCDATA)>
<!ATTLIST deleteIndex
        xmlns CDATA #FIXED ''>

<!ELEMENT nucl (#PCDATA)>
<!ATTLIST nucl
        xmlns CDATA #FIXED ''>

<!ELEMENT newNucl (#PCDATA)>
<!ATTLIST newNucl
        xmlns CDATA #FIXED ''>

<!ELEMENT oldNucl (#PCDATA)>
<!ATTLIST oldNucl
        xmlns CDATA #FIXED ''>

<!ELEMENT reverseIndex (#PCDATA)>
<!ATTLIST reverseIndex
        xmlns CDATA #FIXED ''>

=== CapSylar/Luke-RNAwalker/test-files/generated_diff.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Diff PUBLIC "hello" "DiffScriptDefinition.dtd">
<Diff>
    <meta>
        <SourceString>212e04aaedde8510415d5cfe8c1ba514</SourceString>
        <DestinationString>10d5e3f4f321294416bd6b418773dd67</DestinationString>
    </meta>
    <EditScript>
        <Update>
            <newNucl>R</newNucl>
            <oldNucl>G</oldNucl>
            <updateIndex>0</updateIndex>
            <reverseIndex>0</reverseIndex>
        </Update>
        <Delete>
            <nucl>U</nucl>
            <deleteIndex>1</deleteIndex>
            <reverseIndex>1</reverseIndex>
        </Delete>
        <Update>
            <newNucl>N</newNucl>
            <oldNucl>A</oldNucl>
            <updateIndex>2</updateIndex>
            <reverseIndex>1</reverseIndex>
        </Update>
        <Update>
            <newNucl>R</newNucl>
            <oldNucl>G</oldNucl>
            <updateIndex>3</updateIndex>
            <reverseIndex>2</reverseIndex>
        </Update>
        <Update>
            <newNucl>N</newNucl>
            <oldNucl>U</oldNucl>
            <updateIndex>4</updateIndex>
            <reverseIndex>3</reverseIndex>
        </Update>
        <Update>
            <newNucl>R</newNucl>
            <oldNucl>A</oldNucl>
            <updateIndex>5</updateIndex>
            <reverseIndex>4</reverseIndex>
        </Update>
        <Delete>
            <nucl>C</nucl>
            <deleteIndex>6</deleteIndex>
            <reverseIndex>5</reverseIndex>
        </Delete>
    </EditScript>
</Diff>

=== CapSylar/Luke-RNAwalker/diff-format.xml
<?xml version= "1.0"?>
<!DOCTYPE Diff PUBLIC "hello" "DiffScriptDefinition.dtd">

<Diff>
    <meta>
        <!--SourceString and DestinationString hashCodes to identify the sequences that this file refers to-->
        <SourceString>123123123</SourceString>
        <DestinationString>123321123</DestinationString>
    </meta>
    <EditScript>
        <Insert>
            <!-- getIndex:index of char in destination string , dropIndex: index to insert character at ( after this index ) -->
            <nucl>R</nucl>
            <insertIndex>4</insertIndex>
        </Insert>
        <Delete>
            <!--index to delete from the source string-->
            <nucl>N</nucl>
            <deleteIndex>4</deleteIndex>
        </Delete>
        <Update>
            <!-- getIndex: index of char in destination string , updateIndex: index of source sequence which we should update to match char -->
            <newNucl>A</newNucl>
            <oldNucl>C</oldNucl>
            <updateIndex>9</updateIndex>
        </Update>
    </EditScript>
</Diff>
