=== CapSylar/Luke-RNAwalker/RNADataBankDefinition.dtd
<?xml encoding="UTF-8"?>

        <!ELEMENT RNADataBank (RNA)+>
        <!ATTLIST RNADataBank
                xmlns CDATA #FIXED ''>

        <!ELEMENT RNA (accession,description,length,sequence)>
        <!ATTLIST RNA
                xmlns CDATA #FIXED ''>

        <!ELEMENT accession (#PCDATA)>
        <!ATTLIST accession
                xmlns CDATA #FIXED ''>

        <!ELEMENT description (#PCDATA)>
        <!ATTLIST description
                xmlns CDATA #FIXED ''>

        <!ELEMENT length (#PCDATA)>
        <!ATTLIST length
                xmlns CDATA #FIXED ''>

        <!ELEMENT sequence (#PCDATA)>
        <!ATTLIST sequence
                xmlns CDATA #FIXED ''>

=== CapSylar/Luke-RNAwalker/test-files/FormattedSequences.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE RNADataBank PUBLIC "hello" "RNADataBankDefinition.dtd">
<RNADataBank>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1910041</description>
        <length>22</length>
        <sequence>AGAAGACAUUCGUGGAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 990453</description>
        <length>20</length>
        <sequence>ACGCCUCCACGUAGUGUCUU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1276105</description>
        <length>19</length>
        <sequence>ACGCCUCCACGAGUGUCUU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1787445</description>
        <length>31</length>
        <sequence>ACCAAGGACUUCAUCUUCUCAGAGCUGCUGU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1085182</description>
        <length>30</length>
        <sequence>UCAUCUUCUCAGAGCUGCUGUCCAACCUGC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1869484</description>
        <length>25</length>
        <sequence>UGUCCAACCUGCACUCGCGUGGGAA</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1058989</description>
        <length>29</length>
        <sequence>UGGAAACGAGAAGACACUCAUGGAGGAGU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1200763</description>
        <length>30</length>
        <sequence>UGGGAACGAGAAGACACUCAUGGAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1144067</description>
        <length>30</length>
        <sequence>UGGGAACGAGAAGACACUCAUGGAGGAGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 24091</description>
        <length>20</length>
        <sequence>GUCGGCCGAGCAGGCACAGC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 166980</description>
        <length>26</length>
        <sequence>UCGCGNGGGAAGAAGAAGACACUCCU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 512565</description>
        <length>30</length>
        <sequence>UGGGAAGAAGAAGACACUCCUGGAGGAGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1009780</description>
        <length>27</length>
        <sequence>GAAGAAGACACUCCUGGAGGAGUCGGC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 2147012</description>
        <length>30</length>
        <sequence>UCUUCUCGGAGCUGCUGUCCAACCUGUACU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1986304</description>
        <length>29</length>
        <sequence>UCUUCUCGGAGCUGCUGUCCAACCUGUAC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1221098</description>
        <length>31</length>
        <sequence>UCUUCUCGGAGCUGCUGUCCAACCUGUACUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1636627</description>
        <length>29</length>
        <sequence>UCGGAACCUGCAGACACUUGUGGAGGAGU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1264639</description>
        <length>30</length>
        <sequence>UCGGAACCUGCAGACACUUGUGGAGGAGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 131993</description>
        <length>29</length>
        <sequence>UCGGAACCAGCAGACACUUGUGGAGGAGU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1531952</description>
        <length>23</length>
        <sequence>UCGGAACCUGCAGACACUUGNGG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 234002</description>
        <length>28</length>
        <sequence>UGGGAACGAGAAGACACUCGUGGAGGCG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1474549</description>
        <length>30</length>
        <sequence>UGGGAACGAGAAGACACUCGUGGAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1002761</description>
        <length>33</length>
        <sequence>UGGGAACGAGAAGACACUCGUGGAGGCGUCGGC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 223982</description>
        <length>30</length>
        <sequence>UGGGAACGAGAAGACACUCGUGUAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 211999</description>
        <length>30</length>
        <sequence>UGGGAACGAGAAGACACUCGUGGAGGUGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 661321</description>
        <length>25</length>
        <sequence>UGGGAACAAGGAGACACUCCUGGAG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1214623</description>
        <length>32</length>
        <sequence>CGUGGGAAGAAGAAGACACUCGUGGAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1509292</description>
        <length>30</length>
        <sequence>UGGGAACAAGAAGACACUCGUGGAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1967195</description>
        <length>31</length>
        <sequence>GGAACAAGAAGACACUCGUGGAGGCGUCGGC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1108639</description>
        <length>22</length>
        <sequence>CAGGUUCCGACGCGAGUACAGG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 363545</description>
        <length>29</length>
        <sequence>AGAGCAGGCACAGCGGUGUGACGAGACUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 922399</description>
        <length>29</length>
        <sequence>UGUGACGAGACUCGCGUGGGAAGAAGAAG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 906903</description>
        <length>24</length>
        <sequence>UCGGAACCUGCAGACACUCGUGGA</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1364921</description>
        <length>30</length>
        <sequence>UGGGAAUGAGAAGACACUCGUGAAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 117689</description>
        <length>30</length>
        <sequence>UGGGAACGAGAAGACACUCAUGUAGGAGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1281168</description>
        <length>30</length>
        <sequence>UGGGAACCAGAAGACACUCGUGGAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 41872</description>
        <length>23</length>
        <sequence>UGGGAACCAGAAGACACUCGNGG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1146599</description>
        <length>30</length>
        <sequence>UGGGAACCAGAGGACACUCGUGGAGGCGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 598192</description>
        <length>22</length>
        <sequence>UGGGAACCAGAAGACACUCGUG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 26816</description>
        <length>30</length>
        <sequence>UGGGAACGAGAAGACACUCCUGGAGGAGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 877192</description>
        <length>24</length>
        <sequence>UCGCGUAGGGACAAGAAGACACUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 424393</description>
        <length>30</length>
        <sequence>UAGGGACAAGAAGACACUCCUGGAGGAGUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 2065381</description>
        <length>30</length>
        <sequence>UCAUCGGCGACAUCAACAUGAACACCAUCA</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1834802</description>
        <length>19</length>
        <sequence>CCAAGGGACAGCAGGACUG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1857061</description>
        <length>29</length>
        <sequence>CACCAUUUAAACUGUAGGCCACAGACUGG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1457954</description>
        <length>19</length>
        <sequence>AGGUGGACAACAAUAAGCG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1878651</description>
        <length>31</length>
        <sequence>CAGAAGUUAGGAAGGGCUGUCACUGGUCCUC</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1576827</description>
        <length>30</length>
        <sequence>UAGUUGGAGAAAGAGAAGCCCUGAUCUCUU</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 1008978</description>
        <length>18</length>
        <sequence>UGGGUUGCUCCAUUAGGG</sequence>
    </RNA>
    <RNA>
        <accession>none</accession>
        <description>rna sequence 211984</description>
        <length>26</length>
